INSERT INTO public.training_modules
  (title, provider, accrediting_body, category, description, nqf_level, duration_hours, credits, min_age, max_age, required_qualification, tags, manual_url, is_accredited, is_active)
SELECT v.title, v.provider, v.accrediting_body, v.category, v.description, v.nqf_level, v.duration_hours, v.credits, v.min_age, v.max_age, v.required_qualification, v.tags, v.manual_url, v.is_accredited, v.is_active
FROM (VALUES
  ('NEMISA: Introduction to Basic Digital Literacy','NEMISA','NEMISA Digital Skills Platform','Digital Skills','Free entry-level digital literacy course on the NEMISA Digital Skills Platform. Covers computer basics, files and folders, internet navigation, email, online safety and productivity tools, with a certificate on successful completion.',3,20,4,16,65,'None',ARRAY['digital literacy','computer basics','internet','email','free'],'https://dsp.nemisa.co.za',true,true),
  ('NEMISA: Mobile Digital Literacy','NEMISA','NEMISA Digital Skills Platform','Digital Skills','Free smartphone-first digital literacy course. Use a mobile device for communication, banking, government e-services, job hunting and data management safely and affordably.',3,15,3,16,65,'None',ARRAY['mobile','digital literacy','smartphone','e-services','free'],'https://dsp.nemisa.co.za',true,true),
  ('NEMISA: Digital Technologies for SMMEs','NEMISA','NEMISA Digital Skills Platform','Digital Skills','Free course helping small, medium and micro enterprises use digital tools for marketing, online presence, digital payments, record keeping and customer engagement.',4,25,5,18,65,'None',ARRAY['smme','entrepreneurship','digital marketing','business','free'],'https://dsp.nemisa.co.za',true,true),
  ('NEMISA x IBM SkillsBuild: Artificial Intelligence Fundamentals','NEMISA','IBM SkillsBuild / STEMpower','Digital Skills','Fully sponsored IBM SkillsBuild track delivered through NEMISA and STEMpower. Introduces AI concepts, machine learning, natural language processing and responsible AI, with an IBM digital credential.',4,20,4,16,60,'Grade 10',ARRAY['ai','ibm skillsbuild','machine learning','free','badge'],'https://nemisa.co.za/',true,true),
  ('NEMISA x IBM SkillsBuild: Cybersecurity Fundamentals','NEMISA','IBM SkillsBuild / STEMpower','Digital Skills','Free IBM SkillsBuild cybersecurity foundation course: threats, social engineering, passwords and authentication, data protection and incident response basics for the South African context.',4,20,4,16,60,'Grade 10',ARRAY['cybersecurity','ibm skillsbuild','online safety','free'],'https://nemisa.co.za/',true,true),
  ('NEMISA x IBM SkillsBuild: Data Analytics Fundamentals','NEMISA','IBM SkillsBuild / STEMpower','Digital Skills','Free data analytics track covering data collection, cleaning, spreadsheets, visualisation and storytelling with data, preparing learners for entry-level data roles.',4,25,5,16,60,'Grade 10',ARRAY['data analytics','spreadsheets','visualisation','ibm skillsbuild','free'],'https://nemisa.co.za/',true,true),
  ('NEMISA x IBM SkillsBuild: Cloud Computing Essentials','NEMISA','IBM SkillsBuild / STEMpower','Digital Skills','Free introduction to cloud computing: service models, deployment models, storage, cloud security and how South African businesses adopt cloud services.',4,18,3,16,60,'Grade 10',ARRAY['cloud','ibm skillsbuild','infrastructure','free'],'https://nemisa.co.za/',true,true),
  ('NEMISA x IBM SkillsBuild: Web Development Foundations','NEMISA','IBM SkillsBuild / STEMpower','Digital Skills','Free foundational web development course covering HTML, CSS, basic JavaScript, responsive design and publishing a first website.',4,30,6,16,60,'Grade 10',ARRAY['web development','html','css','javascript','free'],'https://nemisa.co.za/',true,true),
  ('NEMISA x IBM SkillsBuild: Professional & Workplace Skills','NEMISA','IBM SkillsBuild / STEMpower','Digital Skills','Free employability track: design thinking, agile teamwork, presentation skills, CV building and interview readiness for the digital economy.',4,15,3,16,60,'None',ARRAY['employability','soft skills','cv','interview','free'],'https://nemisa.co.za/',true,true),
  ('NEMISA AI: Intro to Artificial Intelligence','NEMISA','NEMISA AI Hub','Digital Skills','Free beginner course from the NEMISA AI course catalogue introducing what artificial intelligence is, where it is used, and its impact on jobs and society.',5,12,2,16,65,'None',ARRAY['ai','beginner','free','nemisa ai'],'https://ai.nemisa.co.za/courses/intro-to-artificial-intelligence/',false,true),
  ('NEMISA AI: Welcome to Artificial Intelligence','NEMISA','NEMISA AI Hub','Digital Skills','Free orientation course to the field of artificial intelligence, its history, core branches and everyday applications.',5,10,2,16,65,'None',ARRAY['ai','orientation','free','nemisa ai'],'https://ai.nemisa.co.za/courses/',false,true),
  ('NEMISA AI: Ethics in the Age of AI Specialization','NEMISA','NEMISA AI Hub','Digital Skills','Free specialisation on ethical questions raised by artificial intelligence: bias, fairness, privacy, accountability and human rights.',6,20,4,18,65,'Grade 12',ARRAY['ai ethics','governance','privacy','free'],'https://ai.nemisa.co.za/courses/ethics-in-the-age-of-ai-specialization/',false,true),
  ('NEMISA AI: Artificial Intelligence Ethics in Action','NEMISA','NEMISA AI Hub','Digital Skills','Free intermediate course applying AI ethics frameworks to real deployment scenarios, risk assessment and responsible AI practice.',6,18,3,18,65,'Grade 12',ARRAY['ai ethics','responsible ai','governance','free'],'https://ai.nemisa.co.za/courses/artificial-intelligence-ethics-in-action/',false,true),
  ('NEMISA AI: Introduction to Metadata and Ontologies','NEMISA','NEMISA AI Hub','Digital Skills','Free intermediate course on metadata standards, knowledge organisation and ontologies as the backbone of intelligent information systems.',6,20,4,18,65,'Grade 12',ARRAY['metadata','ontology','knowledge management','free'],'https://ai.nemisa.co.za/courses/introduction-to-metadata-and-ontologies/',false,true),
  ('NEMISA AI: Practical Knowledge Modelling — Ontology Development 101','NEMISA','NEMISA AI Hub','Digital Skills','Free hands-on course in building ontologies and knowledge models, from concept mapping to implementation in modelling tools.',6,24,5,18,65,'Grade 12',ARRAY['ontology','knowledge modelling','semantic web','free'],'https://ai.nemisa.co.za/courses/practical-knowledge-modelling-ontology-development-101/',false,true),
  ('NEMISA AI: Artificial Intelligence Markup Language (AIML)','NEMISA','NEMISA AI Hub','Digital Skills','Free course teaching AIML for building rule-based conversational agents and chatbots.',5,16,3,18,65,'Grade 12',ARRAY['aiml','chatbots','conversational ai','free'],'https://ai.nemisa.co.za/courses/',false,true),
  ('NEMISA AI: Building a Facebook Chatbot in Chatfuel','NEMISA','NEMISA AI Hub','Digital Skills','Free practical course building a customer-service chatbot on Facebook Messenger using Chatfuel — ideal for small businesses and recruiters.',5,12,2,18,65,'None',ARRAY['chatbot','chatfuel','social media','smme','free'],'https://ai.nemisa.co.za/courses/',false,true),
  ('NEMISA AI: Artificial Intelligence in Bioinformatics','NEMISA','NEMISA AI Hub','Digital Skills','Free course exploring how AI and machine learning are applied to biological and health data, genomics and bio-inspired computing.',7,24,5,18,65,'Grade 12',ARRAY['bioinformatics','ai','health data','free'],'https://ai.nemisa.co.za/courses/',false,true),
  ('NEMISA AI: Music Editing with Deep Learning','NEMISA','NEMISA AI Hub','Digital Skills','Free creative-tech course using deep learning models for audio and music editing, generation and production workflows.',6,18,3,18,65,'None',ARRAY['deep learning','music','audio','creative','free'],'https://ai.nemisa.co.za/courses/',false,true)
) AS v(title, provider, accrediting_body, category, description, nqf_level, duration_hours, credits, min_age, max_age, required_qualification, tags, manual_url, is_accredited, is_active)
WHERE NOT EXISTS (
  SELECT 1 FROM public.training_modules t WHERE t.title = v.title
);